# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-18 14:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='name_coupon',
        ),
        migrations.AddField(
            model_name='coupons',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupons',
            name='code',
            field=models.CharField(default='No Data', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='coupons',
            name='expiration',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
