# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-18 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20220618_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='expiration',
            field=models.DateField(),
        ),
    ]
